import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import "../theme/text-theme.css";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { auth } from "@/auth";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by Tuon",
};

export default async function AdminDashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  if (!session) redirect("/login");
  return (
    <ReactQueryProvider>
      <section className={inter.className}>
        <nav></nav>
        {children}
      </section>
    </ReactQueryProvider>
  );
}
